Default: &defaults
  database: waiter.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: waiter_test.sqlite3
  <<: *defaults

Staging:
  database: waiter_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: waiter_production.sqlite3
  poolsize: 100
  <<: *defaults
